config/routes.rb
Rails.application.routes.draw do
  devise_for :companys, controllers: {
    sessions: 'companys/sessions',
    passwords: 'companys/passwords',
    registrations: 'companys/registrations'
  }
  get 'companys/end_list'
  resources :companys, only: %i[show edit update]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  get 'users/end_list'
  resources :users, only: %i[show edit update]


  root to: 'losstops#index'
  resources :losstops, only: [:index]


  get 'bazaars/search'
  resources :bazaars do
    resources :review_bazaars, only: [:create]
    resources :order_bazaars, only: %i[new create show destroy] do
      resources :contact_bazaars, only: [:create]
    end
  end


  get 'auctions/search'
  resources :auctions do
    resources :review_auctions, only: [:create]
    resources :order_auctions, only: %i[new create show destroy] do
      resources :contact_auctions, only: [:create]
    end
  end

  resources :notice_companys, only: :index
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :name
    validates :first_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]/, message: 'は、全角「漢字・ひらがな・カタカナ」で入力してください。' }
    validates :last_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]/, message: 'は、全角「漢字・ひらがな・カタカナ」で入力してください。' }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'は、全角カタカナで入力してください。' }
    validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'は、全角カタカナで入力してください。' }
    validates :birthday
  end

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
  validates :password, format: { with: VALID_PASSWORD_REGEX, message: 'は、半角の英数字両方を使用してください。' }

  with_options dependent: :destroy do
    has_many :active_notice_companies, class_name: 'NoticeCompany', foreign_key: 'visitor_user_id'

    has_many :order_bazaars
    has_many :contact_bazaars
    has_many :review_bazaars

    has_many :auctions
    has_many :order_auctions
    has_many :contact_auctions
    has_many :review_auctions
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: %i[name profile first_name last_name first_name_kana last_name_kana birthday])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name profile])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update]
  before_action :set_endlist, only: %i[end_list]
  before_action :set_information, only: %i[show end_list]

  def show
  end

  def end_list
  end

  def edit
  end

  def update
  end


  private
  def set_user
    @user = User.find(params[:id])
  end

  def set_endlist
    @user = User.find(current_user.id)
  end

  def set_information
    @auctions = @user.auctions
    @order_bazaars = @user.order_bazaars
    @order_auctions = @user.order_auctions
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/end_list.erb
<%= stylesheet_link_tag 'users/show', :media => "all" %>

<div class="my-page-wrap">
  <div class="guide">
    <h1><u>終了した買いたい物・取引の一覧</u></h1>

    <div>
      <%= link_to "進行中の買いたい物・取引へ戻る", user_path(current_user.id), class: "edit-button" %>
    </div>
  </div>

  <br><br><br>
  <p class="text1">公開を終了した買いたい物</p>
  <div class="auction-container">
    <table class="auctions">
      <tr>
        <th class="number">出品番号</th>
        <th class="auction-title">タイトル</th>
        <th class="auction-price">予算</th>
        <th class="auction-stock">公開期間</th>
      </tr>

      <% @user.auctions.each do |auction| %>
        <% if (auction.deadline < Time.new) || (auction.active == "close") %>
          <tr>
            <td class="number"><%= auction.id %></td>
            <td class="auction-title"><%= link_to auction.title, auction_path(auction.id), class: "blocks" %>
            <td class="auction-price"><%= auction.price %>円</td>
            <td class="auction-deadline"><%= auction.deadline %>まで</td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>


  <% if user_signed_in? %>
    <% if @user.id == current_user.id %>
      <p class="text1">取引が終了したバザー</p>

      <div class="orders-container">
        <table class="orders">
          <tr>
            <th class="order-number">部屋番号</th>
            <th class="order-title">商品名</th>
            <th>お相手のお名前</th>
            <th class="order-link">リンク</th></tr>
            <% @user.order_bazaars.each do |order| %>
              <% if order.active == "close" %>
                <tr>
                  <td class="order-number"><%= order.id %></td>
                  <td class="order-title"><%= link_to order.bazaar.title, bazaar_path(order.bazaar.id), class: "blocks" %></td>
                  <td class="customer"><%= order.company.name %></td>
                  <td class="order-link"><%= link_to "連絡部屋へ", bazaar_order_bazaar_path(order.id, order.bazaar.id), class: "link-button2" %></td>
                </tr>
              <% end %>
            <% end %>
        </table>
      </div>


      <p class="text1">取引が終了したオークション</p>
      <div class="orders-container">
        <table class="orders">
          <tr>
            <th class="order-number">部屋番号</th>
            <th class="order-title">タイトル</th>
            <th class="customer">お相手のお名前</th>
            <th class="order-link">リンク</th>
          </tr>

          <% @user.order_auctions.each do |order| %>
            <% if order.active == "close" %>
              <tr>
                <td class="order-number"><%= order.id %></td>
                <td class="order-title"><%= link_to order.auction.title, auction_path(order.auction.id), class: "blocks" %></td>
                <td class="customer"><%= order.company.name %></td>
                <td class="order-link"><%= link_to "連絡部屋へ", auction_order_auction_path(order.id, order.auction.id), class: "link-button2" %></td>
              </tr>
            <% end %>
          <% end %>
        </table>
      </div>
    <% end %>
  <% end %>
</div>
<%= render 'shared/footer' %>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'users/show', :media => "all" %>

<div class="my-page-wrap">
  <div class="guide">
    <h1><u><%= @user.name %>さんのマイページ</u></h1>

    <div>
      <% if user_signed_in? && @user.id == current_user.id %>
        <%= link_to "マイページの編集", edit_user_registration_path(@user.id), class: "edit-button" %>
      <% end %>
    </div>
  </div>

  <div class="profile-container">
    <table class="profile">
      <tr>
        <td>ユーザー名：<%= @user.name %></td>
      </tr>

      <%=  %>
      <tr>
        <td>紹介PR
        <p class="description"><%= @user.profile %></p></td>
      </tr>
    </table>
  </div>



  <div class="auction-info">
    <p class="text1">公開中の買いたい物</p>

    <% if user_signed_in? %>
      <% if @user.id == current_user.id %>
        <%= link_to "終了した買いたい物・取引一覧へ", users_end_list_path(current_user.id), class: "edit-button" %>
      <% end %>
    <% end %>
  </div>
  <div class="auction-container">
    <table class="auctions">
      <tr>
        <th class="number">出品番号</th>
        <th class="auction-title">タイトル</th>
        <th class="auction-price">予算</th>
        <th class="auction-stock">公開期間</th>
      </tr>

      <% @user.auctions.each do |auction| %>
        <% if (auction.deadline > Time.new) && (auction.active == "active") %>
          <tr>
            <td class="number"><%= auction.id %></td>
            <td class="auction-title"><%= link_to auction.title, auction_path(auction.id), class: "blocks" %>
            <td class="auction-price"><%= auction.price %>円</td>
            <td class="auction-deadline"><%= auction.deadline %>まで</td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>


  <% if user_signed_in? %>
    <% if @user.id == current_user.id %>
      <p class="text2">以下はこのアカウント本人のみに見えています。</p>
      <p class="text1">取引中のバザー</p>

      <div class="orders-container">
        <table class="orders">
          <tr>
            <th class="order-number">部屋番号</th>
            <th class="order-title">商品名</th>
            <th>お相手のお名前</th>
            <th class="order-link">リンク</th>
          </tr>
          <% @user.order_bazaars.each do |order| %>
            <% if order.active == "active" %>
              <tr>
                <td class="order-number"><%= order.id %></td>
                <td class="order-title"><%= link_to order.bazaar.title, bazaar_path(order.bazaar.id), class: "blocks" %></td>
                <td class="customer"><%= order.company.name %></td>
                <td class="order-link"><%= link_to "連絡部屋へ", bazaar_order_bazaar_path(order.id, order.bazaar.id), class: "link-button2" %></td>
              </tr>
            <% end %>
          <% end %>
        </table>
      </div>


      <p class="text1">取引中のオークション</p>
      <div class="orders-container">
        <table class="orders">
          <tr>
            <th class="order-number">部屋番号</th>
            <th class="order-title">タイトル</th>
            <th class="customer">お相手のお名前</th>
            <th class="order-link">リンク</th>
          </tr>

          <% @user.order_auctions.each do |order| %>
            <% if order.active == "active" %>
              <tr>
                <td class="order-number"><%= order.id %></td>
                <td class="order-title"><%= link_to order.auction.title, auction_path(order.auction.id), class: "blocks" %></td>
                <td class="customer"><%= order.company.name %></td>
                <td class="order-link"><%= link_to "連絡部屋へ", auction_order_auction_path(order.id, order.auction.id), class: "link-button2" %></td>
              </tr>
            <% end %>
          <% end %>
        </table>
      </div>
    <% end %>
  <% end %>
</div>
<%= render 'shared/footer' %>