config/routes.rb
Rails.application.routes.draw do
  devise_for :companys, controllers: {
    sessions: 'companys/sessions',
    passwords: 'companys/passwords',
    registrations: 'companys/registrations'
  }
  get 'companys/end_list'
  resources :companys, only: %i[show edit update]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  get 'users/end_list'
  resources :users, only: %i[show edit update]


  root to: 'losstops#index'
  resources :losstops, only: [:index]


  get 'bazaars/search'
  resources :bazaars do
    resources :review_bazaars, only: [:create]
    resources :order_bazaars, only: %i[new create show destroy] do
      resources :contact_bazaars, only: [:create]
    end
  end


  get 'auctions/search'
  resources :auctions do
    resources :review_auctions, only: [:create]
    resources :order_auctions, only: %i[new create show destroy] do
      resources :contact_auctions, only: [:create]
    end
  end

  resources :notice_companys, only: :index
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div>
    <ul>
      <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-wrap">

  <br><p>こちらもまだ何もない</p>

</div>

app/views/shared/_header.html.erb
<%= stylesheet_link_tag 'header', :media => "all" %>

<div class="header-wrap">
  <div class="header-links">
    <div class="logo">
      <%= link_to image_tag("header/logo.png", class:"", size: '180x130'), root_path %>
    </div>

    <ul class="top-lists">
      <li class="top-list">
        <%= link_to(bazaars_path) do %>
          <p>バザー</p>
          <%= image_tag 'header/to_bazaar.png' , size: '80x80' %>
        <% end %>
      </li>

      <li class="top-list">
        <%= link_to(auctions_path, class: 'to-auction') do %>
          <p>オークション</p>
          <%= image_tag 'header/to_auction.png' , size: '80x80' %>
        <% end %>
      </li>
    </ul>
  </div>


  <div class="header-menus">
    <ul class="menu-lists">
      <% if company_signed_in? %>
        <li class="menu-list">
          <%= link_to(company_path(current_company.id)) do %>
            <p>マイページ</p>
            <%= image_tag 'header/mypage.png' , size: '45x80' %>
          <% end %>
        </li>
      <% elsif user_signed_in? %>
        <li class="menu-list">
          <%= link_to(user_path(current_user.id)) do %>
            <p>マイページ</p>
            <%= image_tag 'header/mypage.png' , size: '45x80' %>
          <% end %>
        </li>
      <% else %>
        <li class="menu-list">
          <%= link_to(new_company_registration_path) do %>
            <p>会社新規登録</p>
            <%= image_tag 'header/company.png' , size: '80x80' %>
          <% end %>
        </li>
      <% end %>

      <%#= お知らせ %>
      <% if company_signed_in? %>
        <li class="menu-list">
        </li>
      <% elsif user_signed_in? %>
        <li class="menu-list">
        </li>
      <% else %>
        <li class="menu-list">
          <%= link_to(new_company_session_path) do %>
            <p>会社ログイン</p>
            <%= image_tag 'header/login.png' , size: '80x80' %>
          <% end %>
        </li>
      <% end %>

      <%#= 出品 %>
      <% if company_signed_in? %>
        <li class="menu-list">
          <%= link_to(new_bazaar_path) do %>
            <p>これを出品！</p>
            <%= image_tag 'header/bazaar.png' , size: '80x80' %>
          <% end %>
        </li>
      <% elsif user_signed_in? %>
        <li class="menu-list">
          <%= link_to(new_auction_path) do %>
            <p>買いたい物を投稿</p>
            <%= image_tag 'header/auction.png' , size: '80x80' %>
          <% end %>
        </li>
      <% else %>
        <li class="menu-list">
          <%= link_to(new_user_registration_path) do %>
            <p>一般新規登録</p>
            <%= image_tag 'header/user.png' , size: '80x80' %>
          <% end %>
        </li>
      <% end %>

      <%#= ログアウト %>
      <% if company_signed_in? %>
        <li class="menu-list">
          <%= link_to(destroy_company_session_path, method: :delete) do %>
            <p>ログアウト</p>
            <%= image_tag 'header/logout.png' , size: '55x80' %>
          <% end %>
        </li>
      <% elsif user_signed_in? %>
        <li class="menu-list">
          <%= link_to(destroy_user_session_path, method: :delete) do %>
            <p>ログアウト</p>
            <%= image_tag 'header/logout.png' , size: '55x80' %>
          <% end %>
        </li>
      <% else %>
        <li class="menu-list">
          <%= link_to(new_user_session_path) do %>
            <p>一般ログイン</p>
            <%= image_tag 'header/login.png' , size: '80x80' %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>