config/routes.rb
Rails.application.routes.draw do
  devise_for :companys, controllers: {
    sessions: 'companys/sessions',
    passwords: 'companys/passwords',
    registrations: 'companys/registrations'
  }
  get 'companys/end_list'
  resources :companys, only: %i[show edit update]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  get 'users/end_list'
  resources :users, only: %i[show edit update]


  root to: 'losstops#index'
  resources :losstops, only: [:index]


  get 'bazaars/search'
  resources :bazaars do
    resources :review_bazaars, only: [:create]
    resources :order_bazaars, only: %i[new create show destroy] do
      resources :contact_bazaars, only: [:create]
    end
  end


  get 'auctions/search'
  resources :auctions do
    resources :review_auctions, only: [:create]
    resources :order_auctions, only: %i[new create show destroy] do
      resources :contact_auctions, only: [:create]
    end
  end

  resources :notice_companys, only: :index
end

app/models/bazaar.rb
class Bazaar < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  with_options presence: true do
    validates :title, :description, :deadline, :active, :image

    validates :price, numericality: { only_integer: true, message: 'は半角数字で入力してください。' }
    validates_inclusion_of :price, in: 300..999_999_999, message: 'は300円から設定可能です。'

    validates :stock, numericality: { only_integer: true, message: 'は半角数字で入力してください。' }
    validates_inclusion_of :stock, in: 1..99_999, message: 'は1〜99,999個まで設定可能です。'
  end

  with_options numericality: { message: 'を選択してください。' } do
    validates :category_id, :delivery_charge_id
  end

  belongs_to :category
  belongs_to :delivery_charge

  has_one_attached :image
  has_many :order_bazaars, dependent: :destroy
  has_many :review_bazaars, dependent: :destroy
  belongs_to :company

  has_many :notice_companys, dependent: :destroy
end

app/controllers/bazaars_controller.rb
class BazaarsController < ApplicationController
  before_action :set_bazaar, only: %i[show edit update destroy]
  before_action :authenticate_company!, only: %i[new create edit update destroy]
  before_action :check_company, only: %i[edit update destroy]
  before_action :deadline_or_stock, only: [:edit, :update]
  before_action :search_bazaar, only: [:index, :search]


  def index
    @bazaars = Bazaar.order('created_at DESC')
  end


  def new
    @bazaar = Bazaar.new
  end


  def create
    @bazaar = Bazaar.new(bazaar_params)
    if @bazaar.save
    else
      render :new
    end
  end


  def show
    @order = @bazaar.order_bazaars
    @review = ReviewBazaar.new
    @reviews = @bazaar.review_bazaars.order('created_at DESC')
  end


  def edit; end


  def update
    if @bazaar.update(bazaar_params)
      redirect_to bazaar_path(params[:id])
    else
      render :edit
    end
  end


  def destroy
    @bazaar.update(active: "close")
    redirect_to bazaars_path
  end


  def search
    @results_bazaar = @b.result
  end


  private

  def bazaar_params
    params.require(:bazaar).permit(:image, :title, :description, :price, :stock, :deadline,
                                    :category_id, :delivery_charge_id).merge(company_id: current_company.id, active: "active")
  end

  def set_bazaar
    @bazaar = Bazaar.find(params[:id])
  end

  def check_company
    redirect_to bazaar_path if @bazaar.company.id != current_company.id
  end

  def search_bazaar
    @b = Bazaar.ransack(params[:q])
  end

  def deadline_or_stock
    if (@bazaar.deadline < Time.now) || (@bazaar.stock == 0)
      redirect_to root_path
    end
  end
end

app/views/bazaars/_form.html.erb
<%= stylesheet_link_tag 'bazaars/new', :media => "all" %>


<%= form_with model: bazaar, id: 'new_bazaar', local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>


  <div class="category-and-submit">
    <div>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {include_blank: 'カテゴリーを選択'}, {class:"form-select1", id:""}) %>
    </div>

    <div>
      <%= f.submit "出品する", class:"form-button2" %>
    </div>
  </div>

  <table class="form-table1">
    <tr>
      <th colspan="3"><span class="form-text1">商品名：<%= f.text_field :title, placeholder:"30文字まで", maxlength:"30", class: "form-title" %></th>
    </tr>

    <tr>
      <td rowspan="2" class="form-image">
        <p class="form-text2">画像ファイルをアップロード</p>
        <div id="image_bazaar"></div>
        <label for="bazaar_image">
          <span class="form-button">画像を選択</span><%= f.file_field :image, id: "bazaar_image" %>
        </label>
      </td>

      <td><span class="form-text1">価格<br>
      <%= f.text_field :price, placeholder:"半角数字" %>円</span></td>
      <td><span class="form-text1">在庫<br>
      <%= f.text_field :stock, placeholder:"半角数字" %>個</span></td>
    </tr>

    <tr>
      <td><span class="form-text1">送料の負担<br></span>
      <%= f.collection_select(:delivery_charge_id, DeliveryCharge.all, :id, :name, {}, {class: "form-select1", id:""}) %></td>
      <td>
        <span class="form-text1">出品期間<br>
        <%= raw sprintf(
                      f.date_select(
                        :deadline,
                        class:'form-select1',
                        id:"",
                        use_month_numbers: true,
                        prompt:'--',
                        start_year: 2021,
                        end_year: (Time.now.year + 5),
                        date_separator: '%s'),
                      "年 ", "月 ") + "日 " %></span>
                        <br>上記の日付で終了
      </td>
    </tr>

    <tr>
      <td colspan="3"><span class="form-text1">商品説明
      <%= f.text_area :description, placeholder:"商品PR(文字数制限無し)", class: "form-description" %></span></td>
    </tr>
  </table>
<% end %>

app/views/bazaars/_main.erb
<div class="bazaar-container">
  <p class="index-guide1">その食品…<br>
  <span class="h1-text">棄てるにはまだ早い！</span></p>


  <p class="index-guide2">最近多いこうした出来事…</h5>
  <table class="bazaar-examples">
    <tr>
      <td><%= image_tag 'bazaar/example1.png' , size: '350x350' %></td>
      <td><%= image_tag 'bazaar/example2.png' , size: '350x350' %></td>
    </tr>
    <tr>
      <td><%= image_tag 'bazaar/example3.png' , size: '350x350' %></td>
      <td><%= image_tag 'bazaar/example4.png' , size: '350x350' %></td>
    </tr>
  </table>


  <p class="index-guide3">諦めていた在庫たち…<br>
  <span class="h2-text">もしかしたら売れるかも！</span></h2>
  <div class="bazaar-index-image">
    <%= image_tag 'bazaar/maybe.png', size: '230x300' %>
  </div>


  <p class="index-guide4">かんたん！4つの出品手順！</p>
  <ul class="bazaar-steps">
    <li><%= image_tag 'bazaar/step1.png' , size: '200x200' %></li>
    <li><%= image_tag 'bazaar/step2.png' , size: '200x200' %></li>
    <li><%= image_tag 'bazaar/step3.png' , size: '200x200' %></li>
    <li><%= image_tag 'bazaar/step4.png' , size: '200x200' %></li>
  </ul>
  <p class="index-guide5">もし諦めていたのなら<br>
  ぜひここで出品してみましょうっ！</p>


  <p class="index-guide6">新着10件</p>

  <% @bazaars.each do |bazaar| %>
    <% if (bazaar.deadline > Time.new) && (bazaar.stock > 0) && (bazaar.active == "active") %>
      <div class="search-result">
        <div class="result-image">
          <%= link_to bazaar_path(bazaar.id) do %>
            <%= image_tag bazaar.image, size: '200x200' %>
          <% end %>
        </div>

        <table class="result-table">
          <tr class="result-title">
            <th colspan="2"><%= link_to bazaar.title, bazaar_path(bazaar.id), class: "result-title" %></th>
            <th>価格：<%= bazaar.price %>円</th>
          </tr>
          <tr class="result-text">
            <td>在庫：<%= bazaar.stock %>個</td>
            <td>出品期間：<%= bazaar.deadline %>まで</td>
            <td><%= bazaar.delivery_charge.name %></td>
          </tr>
        </table>
      </div>
    <% else %>
    <% end %>
  <% end %>
</div>

app/views/bazaars/_search.erb
<div class="search-wrap">
  <%= search_form_for @b, url: bazaars_search_path do |f| %>

    <%= image_tag 'search/key_word.png', size: '20x20' %>キーワード検索<br>
    <%= f.search_field :title_cont, placeholder:"(例：牛", class: "search-field" %>
    <br><br>

    <%= image_tag 'search/question.png' , size: '20x20' %>カテゴリーで探す<br>
    <%= f.collection_select :category_id_eq, Category.all, :id, :name, include_blank: '指定なし' %>
    <br><br>

    <%= image_tag 'search/yen.png' , size: '20x20' %>価格で絞り込む<br>
    <%= f.search_field :price_gteq, placeholder:"○○円以上", class: "search-field" %>
    <br>
    <%= f.search_field :price_lteq, placeholder:"○○円以下", class: "search-field" %>
    <br><span class="price-search">片方だけでも検索できます。
    <br>※5000円以下で検索など</span>
    <br><br>

    <%= f.submit '検索' %>
  <% end %>
</div>

app/views/bazaars/_search_commit.html.erb
<div class="commit-wrap">

  <div class="search-nav-container">
    <p class="commit-text">検索結果</p>
    <div>
      <p class="nav-guide">クリックで順番を入れ替え</p>
      <ul class="search-nav-list">
        <li class="search-nav"><%= sort_link(@b, :created_at, "新着") %></li>
        <li class="search-nav"><%= sort_link(@b, :price, "価格") %></li>
        <li class="search-nav"><%= sort_link(@b, :stock, "在庫") %></li>
      </ul>
    </div>
  </div>

  <div class="search-result-container">
    <% if @results_bazaar.length !=0 %>
      <% @results_bazaar.each do |result| %>
        <% if (result.deadline > Time.new) && (result.stock > 0) && (result.active == "active") %>
          <div class="search-result">
            <div class="result-image">
              <%= link_to bazaar_path(result.id) do %>
                <%= image_tag result.image %>
              <% end %>
            </div>

            <table class="result-table">
              <tr class="result-title">
                <th colspan="2"><%= link_to result.title, bazaar_path(result.id), class: "result-title" %></th>
                <th>価格<br><%= result.price %>円</th>
              </tr>
              <tr class="result-text">
                <td>在庫：<%= result.stock %>個</td>
                <td>出品期間：<%= result.deadline %>まで</td>
                <td><%= result.delivery_charge.name %></td>
              </tr>
            </table>
          </div>
        <% end %>
      <% end %>
    <% else %>
      該当する商品はありません
    <% end %>
  </div>
</div>

app/views/bazaars/create.html.erb
<%= stylesheet_link_tag 'bazaars/create', :media => "all" %>
<div class="create-wrap">

  <div>
    <p class="create-text1">出品が完了しました</p>
  </div>

  <div class="create-menus">
    <p><%= link_to '商品ページへ', bazaar_path(@bazaar.id), class: "create-menu" %></p>
    <p><%= link_to '出品を続ける', new_bazaar_path, class: "create-menu" %></p>
    <p><%= link_to 'バザートップへ', bazaars_path, class: "create-menu" %></p>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/bazaars/edit.html.erb
<div class="form-wrap">
  <p class="new-guide1">情報を編集する</p>
  <p class="new-guide2">商品の内容を変更できます。</p>

  <%= render partial: "form", locals: { bazaar: @bazaar }%>
</div>

app/views/bazaars/index.html.erb
<%= stylesheet_link_tag 'search', :media => "all" %>
<%= stylesheet_link_tag 'bazaars/top', :media => "all" %>

<div class="bazaar-wrapper">

  <div class="bazaar-search">
    <%= render "search" %>
  </div>

  <div class="bazaar-top">
    <%= render "main" %>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/bazaars/new.html.erb
<div class="form-wrap">
  <p class="new-guide1">出品する</p>
  <p class="new-guide2">内容は全て記入必須です。</p>

  <%= render partial: "form", locals: { bazaar: @bazaar }%>
</div>

app/views/bazaars/search.html.erb
<%= stylesheet_link_tag 'search', :media => "all" %>
<%= stylesheet_link_tag 'bazaars/top', :media => "all" %>

<div class="bazaar-wrapper">

  <div class="bazaar-search">
    <%= render "search" %>
  </div>

  <div class="search-commit">
    <%= render "search_commit" %>
  </div>

</div>

app/views/bazaars/show.html.erb
<%= stylesheet_link_tag 'bazaars/show', :media => "all" %>
<div class="show-wrap">
<% count = 0 %>

  <div class="introduce-and-room">
    <p class="introduce">商品の詳細</p>

    <div class="rooms">
      <% @order.each do |order| %>
        <% if (current_company.nil?) && (order.user_id == current_user.id) %>
          <%= link_to "取引連絡部屋へ", bazaar_order_bazaar_path(order.id), class: "go-room-button" %>
          <% count += 1 %>
        <% end %>
      <% end %>
      <% if company_signed_in? %>
        <% if current_company.id == @bazaar.company.id %>
            ユーザーからの取引希望の連絡部屋はページ下部に一覧で表示されます。
            <br>※このメッセージは出品者本人にのみ見えています。
        <% end %>
      <% end %>
    </div>
  </div>



  <div class="category-and-submit">
    <p>カテゴリー：<%= @bazaar.category.name %></p>

    <div>
      <% if @bazaar.stock != 0 %>
        <% if (@bazaar.deadline > Time.now) && (@bazaar.active == "active") %>
          <% if (company_signed_in?) && (current_company.id == @bazaar.company.id) %>
            <%= link_to "商品の編集", edit_bazaar_path(@bazaar.id), method: :get, class: "show-button" %>
            <%= link_to "この出品を終了する", bazaar_path(@bazaar.id), method: :delete, class:"show-button" %>
          <% elsif user_signed_in? %>
            <% if count == 0 %>
              <%= link_to "購入を希望する", new_bazaar_order_bazaar_path(@bazaar.id) ,class:"show-button"%>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>


  <table class="form-table1">
    <tr>
      <th colspan="3">出品：<%= @bazaar.company.name %></th>
    </tr>
    <tr>
      <td colspan="3"><span class="show-text1">商品名：<%= @bazaar.title %></span></td>
    </tr>

    <tr>
      <td rowspan="2" class="form-image">
        <div id="image_bazaar">
          <%= image_tag @bazaar.image ,class:"" %>
        </div>
      </td>
      <td><span class="show-text1">価格<br>
        <%= @bazaar.price %>円</span></td>
      <td><span class="show-text1">在庫<br>
        <%= @bazaar.stock %>個</span></td>
    </tr>

    <tr>
      <td><span class="show-text1">送料<br>
        <%= @bazaar.delivery_charge.name %></span></td>
      <td>
        <span class="show-text1">出品期間<br>
        <%= @bazaar.deadline %></span>まで
      </td>
    </tr>
    <tr>
      <td colspan="3"><span class="show-text1">商品説明</span>
      <p class="show-description"><%= @bazaar.description %></p></td>
    </tr>
  </table>

  <% if company_signed_in? %>
    <% if @bazaar.company.id == current_company.id %>
      <p class="contact-guide">この一覧は出品者にのみ見えています。</p>
      <table class="contact-table">
        <tr><th>部屋番号</th><th>お相手のお名前</th><th>リンク</th></tr>
          <% @bazaar.order_bazaars.each do |order| %>
            <tr>
              <td><%= order.id %></td><td><%= order.user.name %></td>
              <td><%= link_to "連絡部屋へ", bazaar_order_bazaar_path(order.id), class: "contact-link" %></td>
            </tr>
          <% end %>
      </table>
    <% end %>
  <% end %>

  <div class="show-reviews">
    <p class="show-text2">ユーザーレビュー</p>

    <div class="review-messages", id='messages'>
      <% @reviews.each do |review| %>

        <div class="review-message">
          <div class="name-and-created">
            <p class="review-name"><%= review.name %></p>
            <p class="review-created"><%= review.created_at %></p>
          </div>

          <p><strong><%= review.comment %></strong></p>
        </div>

      <% end %>
    </div>

    <% if user_signed_in? || company_signed_in? %>
      <%= form_with model: @review, url: bazaar_review_bazaars_path(bazaar_id: @bazaar.id), class: "review-form" do |f| %>
        <div class="review-text-submit">
          <%= f.submit "書き込む" ,class: "review-button"%>
        </div>
        <%= f.text_area :comment, placeholder: "レビュー入力", rows: "2", class: "review-textarea" %>
      <% end %>
    <% end %>
  </div>
</div>